In [2]:
import numpy as np

# NumPy Basics

In [11]:
print(np.__version__)

1.24.0


In [55]:
a = np.array([1,2,3,4,5,6,7,8])

In [46]:
b = np.array([11,12,13,14,15,16])

In [47]:
print(a)

[1 2 3 4 5 6]


In [48]:
print(a.shape)

(6,)


In [49]:
print(a.ndim)

1


In [51]:
print(a.size)

6


In [52]:
a=np.sqrt(a)

In [53]:
print(a)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [64]:
a[:-2]

array([1, 2, 3, 4])

In [66]:
a[1:-2]

array([2, 3, 4])

In [70]:
c = np.array([[1,2],[3,4],[5,6]])
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [71]:
c.shape

(3, 2)

In [74]:
c>2

array([[False, False],
       [ True,  True],
       [ True,  True]])

# Boolean Mask

In [100]:
c[c>2]

array([3, 4, 5, 6])

# NumPy `where()`

In [103]:
# where(argument, if true, if false)

np_where_version = np.where(c>2,'num','not > 2')
print(np_where_version)

[['not > 2' 'not > 2']
 ['num' 'num']
 ['num' 'num']]


# Fancy Indexing

In [ ]:
# Fancy Indexing
# Using a list as index

In [88]:
num_list = np.array([11,666,7,13,42,6,88,42])
print(num_list)
index_list = [1,2,3]
print(num_list[index_list])

[ 11 666   7  13  42   6  88  42]
[666   7  13]


# NumPy `argwhere()`

In [97]:
even = np.argwhere(num_list%2==0).flatten()

In [102]:
# Returns Index
print(even)

[1 4 5 6 7]


In [96]:
print(num_list[even])

[[666]
 [ 42]
 [  6]
 [ 88]
 [ 42]]


# NumPy Broadcasting

In [105]:
x = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])

In [106]:
a = np.array([2,4,6])

In [107]:
y=x+a

In [108]:
print(y)

[[ 3  6  9]
 [ 6  9 12]
 [ 3  6  9]
 [ 6  9 12]]
